# docker-compose.yml

services:

  nginx:

    container_name: nginx

    build: ./docker/nginx

    command: nginx -g "daemon off;"

    links:

      - php

    ports:

      - "80:80"

    volumes:

      -  ./logs/nginx:/var/log/nginx

      - ./src:/var/www/html

  php:

    container_name: php

    build: ./docker/php

    ports:

      - "9000:9000"

    volumes:

      - ./src:/var/www/html

    working_dir: /var/www/html

  mysql:

    image: mysql:8.4.2

    container_name: mysql

    environment:

      MYSQL_ROOT_PASSWORD: sdkf-Qxkl23

      MYSQL_DATABASE: testdb

      MYSQL_USER: sqluser

      MYSQL_PASSWORD: kld!x.klkwe

    ports:

      - "3306:3306"

    volumes:

      - ./database/mysql:/var/lib/mysql

  phpmyadmin:

    image: phpmyadmin/phpmyadmin

    container_name: pma

    links:

      - mysql

    environment:

      PMA_HOST: mysql

      PMA_PORT: 3306

      PMA_ARBITRARY: 1

    restart: always

    ports:

      - 8085:80