name: Daily Build

on:
  schedule:
    - cron: '0 0 * * *' 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: https://github.com/SelinaFriesenbichler/nginx-php-mysql.git
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PASSWORD }}

      - name: Build and push Docker image
        run: |

          compose require tinymce/tinymce
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add package*.json
          git commit -m "Daily Build: Upgrade TinyMCE to latest version"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.PASSWORD }}
