name: Daily Build

on:
  schedule:
    - cron: '0 0 * * *' 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: https://github.com/SelinaFriesenbichler/nginx-php-mysql.git
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PASSWORD }}

     - name: Update TinyMCE
        run: |
          docker-compose run web sh -c "curl -L https://cdn.tiny.cloud/1/no-api-key/tinymce/6/tinymce.min.js -o /usr/share/nginx/html/tinymce.min.js"
          docker-compose run web sh -c "echo '<script src=\"tinymce.min.js\"></script>' > /usr/share/nginx/html/index.html"

      - name: Commit and push changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Daily Build: Update TinyMCE to latest version" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.PASSWORD }}
